### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by abudusamad**

### CODE REVIEW

**Comment by Davronov-Alimardon** [comment]
Please don't PR here, this is my code, you can clone it yourself and work in another repository, but don't send a Pull Request here.

**Comment by abudusamad** [comment]
Okay but I'm not altering your code

**Comment by Davronov-Alimardon** [comment]
Yes, I understand you, but the codes here are linked for a live site, and if one wrong change is made, the site may experience problems. You can easily use Canva Clone by opening your own repository.

**Comment by Davronov-Alimardon** [comment]
You are doing a good job. I wish you luck in your work

**Pull request closed without merging**
